/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author Giannhs Manolas
 */
public class CheckBox_Ergasia extends javax.swing.JFrame {

    public static ArrayList<String> CheckBox_Ergasia = new ArrayList<>();
    private String alla1="False";
    /**
     * Creates new form CheckBox_Ergasia
     */
    public CheckBox_Ergasia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Deksiotites = new javax.swing.JLabel();
        akadimaiki_ekpedeusi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Alla = new javax.swing.JTextArea();
        ypodiksi1 = new javax.swing.JLabel();
        Epikononiaki_ikanotita = new javax.swing.JCheckBox();
        Autopepithisi = new javax.swing.JCheckBox();
        Drastiriopoihsi = new javax.swing.JCheckBox();
        Protovoulia = new javax.swing.JCheckBox();
        Epiteuksi_stoxo = new javax.swing.JCheckBox();
        Autognosia = new javax.swing.JCheckBox();
        Analipsi_euthinon = new javax.swing.JCheckBox();
        Eufuia = new javax.swing.JCheckBox();
        Se_omadiko_plasio = new javax.swing.JCheckBox();
        Igetiki_ikanotita = new javax.swing.JCheckBox();
        Prototipi_skepsi = new javax.swing.JCheckBox();
        Ikanotita_diaxirisis_antitheseon = new javax.swing.JCheckBox();
        Ithiki_deontologia = new javax.swing.JCheckBox();
        Diaprosopikes_sxesis = new javax.swing.JCheckBox();
        Mati1 = new javax.swing.JLabel();
        Mati2 = new javax.swing.JLabel();
        Mati3 = new javax.swing.JLabel();
        Mati4 = new javax.swing.JLabel();
        Mati5 = new javax.swing.JLabel();
        Mati6 = new javax.swing.JLabel();
        Mati7 = new javax.swing.JLabel();
        Mati8 = new javax.swing.JLabel();
        Mati9 = new javax.swing.JLabel();
        Mati10 = new javax.swing.JLabel();
        Mati11 = new javax.swing.JLabel();
        Mati12 = new javax.swing.JLabel();
        Mati13 = new javax.swing.JLabel();
        Mati14 = new javax.swing.JLabel();
        Epomeno = new javax.swing.JButton();
        Prohgoymeno = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        New = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        About = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("e-πιστολή");
        setResizable(false);
        setSize(800, 700);

        Deksiotites.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Deksiotites.setText("Δεξιότητες");

        akadimaiki_ekpedeusi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        akadimaiki_ekpedeusi.setText("Για εργασία");

        Alla.setColumns(20);
        Alla.setRows(5);
        Alla.setText("Άλλα...");
        Alla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Alla);

        ypodiksi1.setText("*Υπόδειξη: Συμπληρώστε κατά προτίμηση από 1 έως 6");

        Epikononiaki_ikanotita.setText("Επικοινωνιακή ικανότητα");
        Epikononiaki_ikanotita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Epikononiaki_ikanotitaActionPerformed(evt);
            }
        });

        Autopepithisi.setText("Αυτοπεποίθηση");
        Autopepithisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutopepithisiActionPerformed(evt);
            }
        });

        Drastiriopoihsi.setText("Δραστηριοποίηση και ευελιξία");
        Drastiriopoihsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrastiriopoihsiActionPerformed(evt);
            }
        });

        Protovoulia.setText("Πρωτοβουλία");
        Protovoulia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProtovouliaActionPerformed(evt);
            }
        });

        Epiteuksi_stoxo.setText("Επίτευξη στόχων");
        Epiteuksi_stoxo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Epiteuksi_stoxoActionPerformed(evt);
            }
        });

        Autognosia.setText("Αυτογνωσία");
        Autognosia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutognosiaActionPerformed(evt);
            }
        });

        Analipsi_euthinon.setText("Προθυμία ανάληψης ευθυνών");
        Analipsi_euthinon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Analipsi_euthinonActionPerformed(evt);
            }
        });

        Eufuia.setText("Ευφυΐα");
        Eufuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EufuiaActionPerformed(evt);
            }
        });

        Se_omadiko_plasio.setText("Ομαδικότητα και συνεργατικότητα ");
        Se_omadiko_plasio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Se_omadiko_plasioActionPerformed(evt);
            }
        });

        Igetiki_ikanotita.setText("Ηγετική ικανότητα");
        Igetiki_ikanotita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Igetiki_ikanotitaActionPerformed(evt);
            }
        });

        Prototipi_skepsi.setText("Πρωτότυπη σκέψη και δράση");
        Prototipi_skepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Prototipi_skepsiActionPerformed(evt);
            }
        });

        Ikanotita_diaxirisis_antitheseon.setText("Ικανότητα διαχείρισης αντιπαραθέσεων");
        Ikanotita_diaxirisis_antitheseon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ikanotita_diaxirisis_antitheseonActionPerformed(evt);
            }
        });

        Ithiki_deontologia.setText("Ηθική/Δεοντολογία");
        Ithiki_deontologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ithiki_deontologiaActionPerformed(evt);
            }
        });

        Diaprosopikes_sxesis.setText("Διαπροσωπικες σχέσεις");
        Diaprosopikes_sxesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diaprosopikes_sxesisActionPerformed(evt);
            }
        });

        Mati1.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati1.setText("jLabel1");
        Mati1.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati1MouseEntered(evt);
            }
        });

        Mati2.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati2.setText("jLabel1");
        Mati2.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati2MouseEntered(evt);
            }
        });

        Mati3.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati3.setText("jLabel1");
        Mati3.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati3MouseEntered(evt);
            }
        });

        Mati4.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati4.setText("jLabel1");
        Mati4.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati4MouseEntered(evt);
            }
        });

        Mati5.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati5.setText("jLabel1");
        Mati5.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati5MouseEntered(evt);
            }
        });

        Mati6.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati6.setText("jLabel1");
        Mati6.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati6MouseEntered(evt);
            }
        });

        Mati7.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati7.setText("jLabel1");
        Mati7.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati7MouseEntered(evt);
            }
        });

        Mati8.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati8.setText("jLabel1");
        Mati8.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati8MouseEntered(evt);
            }
        });

        Mati9.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati9.setText("jLabel1");
        Mati9.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati9MouseEntered(evt);
            }
        });

        Mati10.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati10.setText("jLabel1");
        Mati10.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati10MouseEntered(evt);
            }
        });

        Mati11.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati11.setText("jLabel1");
        Mati11.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati11MouseEntered(evt);
            }
        });

        Mati12.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati12.setText("jLabel1");
        Mati12.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati12MouseEntered(evt);
            }
        });

        Mati13.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati13.setText("jLabel1");
        Mati13.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati13MouseEntered(evt);
            }
        });

        Mati14.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati14.setText("jLabel1");
        Mati14.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati14MouseEntered(evt);
            }
        });

        Epomeno.setText("Επόμενο");
        Epomeno.setToolTipText("");
        Epomeno.setPreferredSize(new java.awt.Dimension(99, 23));
        Epomeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EpomenoActionPerformed(evt);
            }
        });

        Prohgoymeno.setText("Προηγούμενο");
        Prohgoymeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProhgoymenoActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(null);

        File.setBorder(null);
        File.setText("File");

        New.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        New.setText("New");
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });
        File.add(New);

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_MASK));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        File.add(Exit);

        jMenuBar1.add(File);

        Help.setBorder(null);
        Help.setText("Help");
        Help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelpMouseClicked(evt);
            }
        });
        jMenuBar1.add(Help);

        About.setText("About");
        About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutMouseClicked(evt);
            }
        });
        jMenuBar1.add(About);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(akadimaiki_ekpedeusi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Autognosia)
                                            .addComponent(Autopepithisi)
                                            .addComponent(Protovoulia)
                                            .addComponent(Drastiriopoihsi)
                                            .addComponent(Epikononiaki_ikanotita)
                                            .addComponent(Epiteuksi_stoxo)
                                            .addComponent(Se_omadiko_plasio)
                                            .addComponent(Eufuia)
                                            .addComponent(Analipsi_euthinon)
                                            .addComponent(Igetiki_ikanotita)
                                            .addComponent(Prototipi_skepsi)
                                            .addComponent(Ithiki_deontologia)
                                            .addComponent(Diaprosopikes_sxesis)
                                            .addComponent(Ikanotita_diaxirisis_antitheseon))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Mati14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Mati12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Mati13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Mati11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Mati10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Mati9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Mati8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Mati7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Mati6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Mati5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Mati4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Mati3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Mati2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Mati1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24))))
                            .addComponent(ypodiksi1))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Deksiotites, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Prohgoymeno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Epomeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Deksiotites)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(akadimaiki_ekpedeusi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Autognosia)
                    .addComponent(Mati1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Autopepithisi)
                    .addComponent(Mati2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Protovoulia)
                    .addComponent(Mati3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Drastiriopoihsi)
                    .addComponent(Mati4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Epikononiaki_ikanotita)
                    .addComponent(Mati5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Epiteuksi_stoxo)
                    .addComponent(Mati6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Se_omadiko_plasio)
                    .addComponent(Mati7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eufuia)
                    .addComponent(Mati8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Analipsi_euthinon)
                    .addComponent(Mati9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Igetiki_ikanotita)
                    .addComponent(Mati10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Prototipi_skepsi)
                    .addComponent(Mati11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ikanotita_diaxirisis_antitheseon)
                    .addComponent(Mati14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Diaprosopikes_sxesis)
                    .addComponent(Mati12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ithiki_deontologia)
                    .addComponent(Mati13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ypodiksi1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Epomeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Prohgoymeno))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void AllaMouseClicked(java.awt.event.MouseEvent evt) {
        alla1 = "True";
        Alla.setText("");
    }                                 

    private void Epikononiaki_ikanotitaActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        if (Epikononiaki_ikanotita.isSelected() == true){
        CheckBox_Ergasia.add("Εφράδης με σαφήνεια και πληρότητα στον λόγο του.");
         }
         else{
             CheckBox_Ergasia.remove("Εφράδης με σαφήνεια και πληρότητα στον λόγο του.");
         }
    }                                                      

    private void AutopepithisiActionPerformed(java.awt.event.ActionEvent evt) {                                              
 if (Autopepithisi.isSelected() == true){
        CheckBox_Ergasia.add("Έχει υψηλή αυτοπεποίθηση με δυναμικό χαρακτήρα.");
         }
         else{
             CheckBox_Ergasia.remove("Έχει υψηλή αυτοπεποίθηση με δυναμικό χαρακτήρα.");
         }  
    }                                             

    private void ProtovouliaActionPerformed(java.awt.event.ActionEvent evt) {                                            
         if (Protovoulia.isSelected() == true){
        CheckBox_Ergasia.add("Παίρνει σημαντικές και δύσκολες αποφάσεις σε κρίσιμες καταστάσεις.");
         }
         else{
             CheckBox_Ergasia.remove("Παίρνει σημαντικές και δύσκολες αποφάσεις σε κρίσιμες καταστάσεις.");
         }
    }                                           

    private void DrastiriopoihsiActionPerformed(java.awt.event.ActionEvent evt) {                                                
         if (Drastiriopoihsi.isSelected() == true){
        CheckBox_Ergasia.add("Δυναμικός και δραστήριος χαρακτήρας που δεν αφήνει καμία ευκαιρία να πάει χαμένη.");
         }
         else{
             CheckBox_Ergasia.remove("Δυναμικός και δραστήριος χαρακτήρας που δεν αφήνει καμία ευκαιρία να πάει χαμένη.");
         }
    }                                               

    private void AutognosiaActionPerformed(java.awt.event.ActionEvent evt) {                                           
         if (Autognosia.isSelected() == true){
        CheckBox_Ergasia.add("Γνωρίζει τα όρια και τις δυνατότητές του.");
         }
         else{
             CheckBox_Ergasia.remove("Γνωρίζει τα όρια και τις δυνατότητές του.");
         }
    }                                          

    private void Epiteuksi_stoxoActionPerformed(java.awt.event.ActionEvent evt) {                                                
         if (Epiteuksi_stoxo.isSelected() == true){
        CheckBox_Ergasia.add("Επίτευξη, επίλυση ακόμη και πρωτότυπων προβλημάτων με δεξιοτεχνία και αποτελεσματικότητα.");
         }
         else{
             CheckBox_Ergasia.remove("Επίτευξη και επίλυση στόχων ακόμη και πρωτότυπων προβλημάτων με δεξιοτεχνία και αποτελεσματικότητα.");
         }
    }                                               

    private void Se_omadiko_plasioActionPerformed(java.awt.event.ActionEvent evt) {                                                  
         if (Se_omadiko_plasio.isSelected() == true){
        CheckBox_Ergasia.add("Επιτυγχάνει, χάρη της συνεργατικότητας και της διάθεσης για εργασία");
         }
         else{
             CheckBox_Ergasia.remove("Επιτυγχάνει, χάρη της συνεργατικότητας και της διάθεσης για εργασία.");
         }
    }                                                 

    private void EufuiaActionPerformed(java.awt.event.ActionEvent evt) {                                       
         if (Eufuia.isSelected() == true){
        CheckBox_Ergasia.add("Έίναι ευφυέστατο άτομο με ώριμη σκέψη.");
         }
         else{
             CheckBox_Ergasia.remove("Έίναι ευφυέστατο άτομο με ώριμη σκέψη.");
         }
    }                                      

    private void Analipsi_euthinonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
         if (Analipsi_euthinon.isSelected() == true){
        CheckBox_Ergasia.add("Πρόθυμος να αναλάβει και να ολοκληρώσει οποιαδήποτε δραστηριότητα.");
         }
         else{
             CheckBox_Ergasia.remove("Πρόθυμος να αναλάβει και να ολοκληρώσει οποιαδήποτε δραστηριότητα.");
         }
    }                                                 

    private void Igetiki_ikanotitaActionPerformed(java.awt.event.ActionEvent evt) {                                                  
         if (Igetiki_ikanotita.isSelected() == true){
        CheckBox_Ergasia.add("Πρόκειται για ένα άτομο που καθοδηγεί και εμπνέει εμπιστοσύνη στα μέλη μιας ομάδας.");
         }
         else{
             CheckBox_Ergasia.remove("Πρόκειται για ένα άτομο που καθοδηγεί και εμπνέει εμπιστοσύνη στα μέλη μιας ομάδας.");
         }
    }                                                 

    private void Prototipi_skepsiActionPerformed(java.awt.event.ActionEvent evt) {                                                 
         if (Prototipi_skepsi.isSelected() == true){
        CheckBox_Ergasia.add("Πρωτοπόρος και καινοτόμος στο χώρο του.");
         }
         else{
             CheckBox_Ergasia.remove("Πρωτοπόρος και καινοτόμος στο χώρο του.");
         }
    }                                                

    private void Ikanotita_diaxirisis_antitheseonActionPerformed(java.awt.event.ActionEvent evt) {                                                                 
         if (Ikanotita_diaxirisis_antitheseon.isSelected() == true){
        CheckBox_Ergasia.add("Σε περίπτωση αντιπαραθέσεων διατηρεί χαρακήρα και αντιμετωπίζει με ψυχραιμία την κατάσταση.");
         }
         else{
             CheckBox_Ergasia.remove("Σε περίπτωση αντιπαραθέσεων διατηρεί χαρακήρα και αντιμετωπίζει με ψυχραιμία την κατάσταση.");
         }
    }                                                                

    private void Ithiki_deontologiaActionPerformed(java.awt.event.ActionEvent evt) {                                                   
         if (Ithiki_deontologia.isSelected() == true){
        CheckBox_Ergasia.add("Μια συνεχώς εξελισσόμενη δυναμική με ηθικές αρχές.");
         }
         else{
             CheckBox_Ergasia.remove("Μια συνεχώς εξελισσόμενη δυναμική με ηθικές αρχές.");
         }
    }                                                  

    private void Diaprosopikes_sxesisActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        if (Diaprosopikes_sxesis.isSelected() == true){
            CheckBox_Ergasia.add("Επιτυγχάνει, χάρη της συνεργατικότητας και της διάθεσης για εργασία");
        }
        else{
            CheckBox_Ergasia.remove("Επιτυγχάνει, χάρη της συνεργατικότητας και της διάθεσης για εργασία");
        }
    }                                                 

    private void Mati1MouseEntered(java.awt.event.MouseEvent evt) {                                   
        Mati1.setToolTipText("Γνωρίζει τα όρια και τις δυνατότητές του.");
    }                                  

    private void Mati2MouseEntered(java.awt.event.MouseEvent evt) {                                   
        Mati2.setToolTipText("Έχει υψηλή αυτοπεποίθηση με δυναμικό χαρακτήρα.");
    }                                  

    private void Mati3MouseEntered(java.awt.event.MouseEvent evt) {                                   
        Mati3.setToolTipText("Παίρνει σημαντικές και δύσκολες αποφάσεις σε κρίσιμες καταστάσεις.");
    }                                  

    private void Mati4MouseEntered(java.awt.event.MouseEvent evt) {                                   
        Mati4.setToolTipText("Δυναμικός και δραστήριος χαρακτήρας που δεν αφήνει καμία ευκαιρία να πάει χαμένη.");
    }                                  

    private void Mati5MouseEntered(java.awt.event.MouseEvent evt) {                                   
        Mati5.setToolTipText("Εφράδης με σαφήνεια και πληρότητα στον λόγο του.");
    }                                  

    private void Mati6MouseEntered(java.awt.event.MouseEvent evt) {                                   
        Mati6.setToolTipText("Επίτευξη στόχων, ακόμα και πρωτότυπων προβλημάτων με δεξιοτεχνία και αποτελεσματικότητα.");
    }                                  

    private void Mati7MouseEntered(java.awt.event.MouseEvent evt) {                                   
        Mati7.setToolTipText("Επιτυγχάνει, χάρη της συνεργατικότητας και της διάθεσης για εργασία");
    }                                  

    private void Mati8MouseEntered(java.awt.event.MouseEvent evt) {                                   
        Mati8.setToolTipText("Έίναι ευφυέστατο άτομο με ώριμη σκέψη.");
    }                                  

    private void Mati9MouseEntered(java.awt.event.MouseEvent evt) {                                   
        Mati9.setToolTipText("Πρόθυμος να αναλάβει και να ολοκληρώσει οποιαδήποτε δραστηριότητα.");
    }                                  

    private void Mati10MouseEntered(java.awt.event.MouseEvent evt) {                                    
        Mati10.setToolTipText("Πρόκειται για ένα άτομο που καθοδηγεί και εμπνέει εμπιστοσύνη στα μέλη μιας ομάδας.");
    }                                   

    private void Mati11MouseEntered(java.awt.event.MouseEvent evt) {                                    
        Mati11.setToolTipText("Πρωτοπόρος και καινοτόμος στο χώρο του.");
    }                                   

    private void Mati12MouseEntered(java.awt.event.MouseEvent evt) {                                    
        Mati12.setToolTipText("Διαπροσωπικές σχέσεις που περιλαμβάνουν υψηλά επίπεδα συνεργασίας, με συχνή αλληλεπίδραση και μεγάλα ποσοστά προσαρμογής.");
    }                                   

    private void Mati13MouseEntered(java.awt.event.MouseEvent evt) {                                    
        Mati13.setToolTipText("Μια συνεχώς εξελισσόμενη δυναμική με ηθικές αρχές.");
    }                                   

    private void Mati14MouseEntered(java.awt.event.MouseEvent evt) {                                    
        Mati14.setToolTipText("Σε περίπτωση αντιπαραθέσεων διατηρεί χαρακήρα και αντιμετωπίζει με ψυχραιμία την κατάσταση.");
    }                                   

    private void EpomenoActionPerformed(java.awt.event.ActionEvent evt) {  
        if(alla1 == "True"){
        CheckBox_Ergasia.add(Alla.getText());
        }
        ArxeioSelect arxeio = new ArxeioSelect();
        arxeio.setVisible(true);
        setVisible(false);
        dispose();

    }                                       

    private void ProhgoymenoActionPerformed(java.awt.event.ActionEvent evt) {      
        
        Agglika_Sunisto.Gnosi = "";
        Agglika_Sunisto.Epipedo = "";
        Agglika_Sunisto.Gnosi_Agglikon = "";
        Agglika_Sunisto.Sinisto = "";
        Agglika_Sunisto ag = new Agglika_Sunisto();
        ag.setVisible(true);
        setVisible(false);
        dispose();
    }                                           

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {                                    
        Oroi_Xrisis ox = new Oroi_Xrisis();
        ox.setVisible(true);
        setVisible(false);
        dispose();
    }                                   

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {                                     
        System.exit(0);
    }                                    

    private void HelpMouseClicked(java.awt.event.MouseEvent evt) {                                  
        Help help = new Help();
        help.setVisible(true);
    }                                 

    private void AboutMouseClicked(java.awt.event.MouseEvent evt) {                                   
        About about = new About();
        about.setVisible(true);
    }                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckBox_Ergasia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckBox_Ergasia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckBox_Ergasia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckBox_Ergasia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckBox_Ergasia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenu About;
    private javax.swing.JTextArea Alla;
    private javax.swing.JCheckBox Analipsi_euthinon;
    private javax.swing.JCheckBox Autognosia;
    private javax.swing.JCheckBox Autopepithisi;
    private javax.swing.JLabel Deksiotites;
    private javax.swing.JCheckBox Drastiriopoihsi;
    private javax.swing.JCheckBox Epikononiaki_ikanotita;
    private javax.swing.JCheckBox Epiteuksi_stoxo;
    private javax.swing.JButton Epomeno;
    private javax.swing.JCheckBox Eufuia;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Help;
    private javax.swing.JCheckBox Igetiki_ikanotita;
    private javax.swing.JCheckBox Ikanotita_diaxirisis_antitheseon;
    private javax.swing.JCheckBox Ithiki_deontologia;
    private javax.swing.JLabel Mati1;
    private javax.swing.JLabel Mati10;
    private javax.swing.JLabel Mati11;
    private javax.swing.JLabel Mati12;
    private javax.swing.JLabel Mati13;
    private javax.swing.JLabel Mati14;
    private javax.swing.JLabel Mati2;
    private javax.swing.JLabel Mati3;
    private javax.swing.JLabel Mati4;
    private javax.swing.JLabel Mati5;
    private javax.swing.JLabel Mati6;
    private javax.swing.JLabel Mati7;
    private javax.swing.JLabel Mati8;
    private javax.swing.JLabel Mati9;
    private javax.swing.JMenuItem New;
    private javax.swing.JButton Prohgoymeno;
    private javax.swing.JCheckBox Prototipi_skepsi;
    private javax.swing.JCheckBox Protovoulia;
    private javax.swing.JCheckBox Se_omadiko_plasio;
    private javax.swing.JCheckBox Diaprosopikes_sxesis;
    private javax.swing.JLabel akadimaiki_ekpedeusi;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ypodiksi1;
    // End of variables declaration                   
}
