/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author Giannhs Manolas
 */
public class CheckBox_Ekpaideush extends javax.swing.JFrame {
    public static List<String> CheckBox_Ekpaideush = new ArrayList<String>();
    private String alla1 ="False";
    private String eidikes ="False";
    private String pedio ="False";
    
    /**
     * Creates new form CheckBox
     */
    public CheckBox_Ekpaideush() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Deksiotites = new javax.swing.JLabel();
        akadimaiki_ekpedeusi = new javax.swing.JLabel();
        Prohgoymeno = new javax.swing.JButton();
        Epomeno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Alla = new javax.swing.JTextArea();
        ypodiksi1 = new javax.swing.JLabel();
        Drastiriotita_kai_thelisi_gia_ergasia = new javax.swing.JCheckBox();
        Dianoitikes_ikanotites = new javax.swing.JCheckBox();
        Ereunitikes_ikanotites = new javax.swing.JCheckBox();
        Synaisthimatiki_statherotita_kai_orimotita = new javax.swing.JCheckBox();
        Syggrafiki_ikanotita = new javax.swing.JCheckBox();
        Synergatikotita = new javax.swing.JCheckBox();
        Dimiourgikotita_kai_prototipia = new javax.swing.JCheckBox();
        Akeraiotita_xaraktira = new javax.swing.JCheckBox();
        Mati1 = new javax.swing.JLabel();
        Mati2 = new javax.swing.JLabel();
        Mati3 = new javax.swing.JLabel();
        Mati4 = new javax.swing.JLabel();
        Mati5 = new javax.swing.JLabel();
        Mati7 = new javax.swing.JLabel();
        Mati8 = new javax.swing.JLabel();
        Mati10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Pedio_spoudon_text = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Eidikes_ikanotites_text = new javax.swing.JTextArea();
        Pedio_spoudon = new javax.swing.JLabel();
        Eidikes_ikanotites = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        New = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        About = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("e-πιστολή");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(800, 700);
        setResizable(false);

        Deksiotites.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Deksiotites.setText("Δεξιότητες");

        akadimaiki_ekpedeusi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        akadimaiki_ekpedeusi.setText("Για ακαδημαϊκή εκπαίδευση");

        Prohgoymeno.setText("Προηγούμενο");
        Prohgoymeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProhgoymenoActionPerformed(evt);
            }
        });

        Epomeno.setText("Επόμενο");
        Epomeno.setToolTipText("");
        Epomeno.setPreferredSize(new java.awt.Dimension(99, 23));
        Epomeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EpomenoActionPerformed(evt);
            }
        });

        Alla.setColumns(20);
        Alla.setRows(5);
        Alla.setText("Άλλα...");
        Alla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Alla);

        ypodiksi1.setText("*Υπόδειξη: Συμπληρώστε κατά προτίμηση από 1 έως 6");

        Drastiriotita_kai_thelisi_gia_ergasia.setText("Δραστηριότητα και θέληση για εργασία");
        Drastiriotita_kai_thelisi_gia_ergasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Drastiriotita_kai_thelisi_gia_ergasiaActionPerformed(evt);
            }
        });

        Dianoitikes_ikanotites.setText("Διανοητικές ικανότητες/εμβρίθεια");
        Dianoitikes_ikanotites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dianoitikes_ikanotitesActionPerformed(evt);
            }
        });

        Ereunitikes_ikanotites.setText("Ερευνητικές ικανότητες");
        Ereunitikes_ikanotites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ereunitikes_ikanotitesActionPerformed(evt);
            }
        });

        Synaisthimatiki_statherotita_kai_orimotita.setText("Συναισθηματική σταθερότητα και ωριμότητα");
        Synaisthimatiki_statherotita_kai_orimotita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Synaisthimatiki_statherotita_kai_orimotitaActionPerformed(evt);
            }
        });

        Syggrafiki_ikanotita.setText("Συγγραφική και εκφραστική ικανότητα.");
        Syggrafiki_ikanotita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Syggrafiki_ikanotitaActionPerformed(evt);
            }
        });

        Synergatikotita.setText("Συνεργατικότητα");
        Synergatikotita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SynergatikotitaActionPerformed(evt);
            }
        });

        Dimiourgikotita_kai_prototipia.setText("Δημιουργικότητα και πρωτοτυπία");
        Dimiourgikotita_kai_prototipia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dimiourgikotita_kai_prototipiaActionPerformed(evt);
            }
        });

        Akeraiotita_xaraktira.setText("Ακεραιότητα χαρακτήρα");
        Akeraiotita_xaraktira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Akeraiotita_xaraktiraActionPerformed(evt);
            }
        });

        Mati1.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati1.setText("jLabel1");
        Mati1.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati1MouseEntered(evt);
            }
        });

        Mati2.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati2.setText("jLabel1");
        Mati2.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati2MouseEntered(evt);
            }
        });

        Mati3.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati3.setText("jLabel1");
        Mati3.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati3MouseEntered(evt);
            }
        });

        Mati4.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati4.setText("jLabel1");
        Mati4.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati4MouseEntered(evt);
            }
        });

        Mati5.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati5.setText("jLabel1");
        Mati5.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati5MouseEntered(evt);
            }
        });

        Mati7.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati7.setText("jLabel1");
        Mati7.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati7MouseEntered(evt);
            }
        });

        Mati8.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati8.setText("jLabel1");
        Mati8.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati8MouseEntered(evt);
            }
        });

        Mati10.setIcon(new javax.swing.ImageIcon(getClass().getResource("mati1.png"))); // NOI18N
        Mati10.setText("jLabel1");
        Mati10.setPreferredSize(new java.awt.Dimension(10, 10));
        Mati10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mati10MouseEntered(evt);
            }
        });

        Pedio_spoudon_text.setColumns(20);
        Pedio_spoudon_text.setRows(5);
        Pedio_spoudon_text.setText("Καλή γνώση του...");
        Pedio_spoudon_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pedio_spoudon_textMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Pedio_spoudon_text);

        Eidikes_ikanotites_text.setColumns(20);
        Eidikes_ikanotites_text.setRows(5);
        Eidikes_ikanotites_text.setText("Επιπλέον ο υποψήφιος διαθέτει...");
        Eidikes_ikanotites_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eidikes_ikanotites_textMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Eidikes_ikanotites_text);

        Pedio_spoudon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Pedio_spoudon.setText("Πεδίο σπουδών");

        Eidikes_ikanotites.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Eidikes_ikanotites.setText("Ειδικές ικανότητες");

        jMenuBar1.setBorder(null);

        File.setBorder(null);
        File.setText("File");

        New.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        New.setText("New");
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });
        File.add(New);

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_MASK));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        File.add(Exit);

        jMenuBar1.add(File);

        Help.setBorder(null);
        Help.setText("Help");
        Help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelpMouseClicked(evt);
            }
        });
        jMenuBar1.add(Help);

        About.setText("About");
        About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutMouseClicked(evt);
            }
        });
        jMenuBar1.add(About);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Prohgoymeno)
                        .addGap(18, 18, 18)
                        .addComponent(Epomeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Deksiotites, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(49, 49, 49)
                                    .addComponent(akadimaiki_ekpedeusi)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ypodiksi1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(Drastiriotita_kai_thelisi_gia_ergasia)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Mati1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Dianoitikes_ikanotites)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Mati2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Ereunitikes_ikanotites)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Mati3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Synaisthimatiki_statherotita_kai_orimotita)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                                                .addComponent(Mati4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Syggrafiki_ikanotita)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Mati5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Synergatikotita)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Mati7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Dimiourgikotita_kai_prototipia)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Mati8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(Akeraiotita_xaraktira)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Mati10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(69, 69, 69))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Eidikes_ikanotites)
                                            .addComponent(Pedio_spoudon))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                                            .addComponent(jScrollPane2))))))
                        .addGap(242, 242, 242))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Deksiotites)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(akadimaiki_ekpedeusi)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Drastiriotita_kai_thelisi_gia_ergasia)
                    .addComponent(Mati1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dianoitikes_ikanotites)
                    .addComponent(Mati2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ereunitikes_ikanotites)
                    .addComponent(Mati3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Synaisthimatiki_statherotita_kai_orimotita)
                    .addComponent(Mati4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Syggrafiki_ikanotita)
                    .addComponent(Mati5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Synergatikotita, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mati7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dimiourgikotita_kai_prototipia)
                    .addComponent(Mati8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Akeraiotita_xaraktira)
                    .addComponent(Mati10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(Pedio_spoudon)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Eidikes_ikanotites)
                        .addGap(51, 51, 51)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ypodiksi1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Prohgoymeno)
                    .addComponent(Epomeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void ProhgoymenoActionPerformed(java.awt.event.ActionEvent evt) {  
        
        Agglika_Sunisto.Gnosi_Agglikon = "";
        Agglika_Sunisto.Sinisto = "";
        Agglika_Sunisto.Gnosi = "";
        Agglika_Sunisto.Epipedo = "";
        Agglika_Sunisto ag = new Agglika_Sunisto();
        ag.setVisible(true);
        setVisible(false);
        dispose();
    }                                           

    private void EpomenoActionPerformed(java.awt.event.ActionEvent evt) {   
          
        if(pedio == "True"){
        CheckBox_Ekpaideush.add(Pedio_spoudon_text.getText());  
        }
        if(eidikes =="True"){
        CheckBox_Ekpaideush.add(Eidikes_ikanotites_text.getText());  
        }
        if(alla1 == "True"){
        CheckBox_Ekpaideush.add(Alla.getText());
        }
        ArxeioSelect arxeio = new ArxeioSelect();
        arxeio.setVisible(true);
        setVisible(false);
        dispose();
        

    }                                       

    private void Drastiriotita_kai_thelisi_gia_ergasiaActionPerformed(java.awt.event.ActionEvent evt) {                                                                      
         if (Drastiriotita_kai_thelisi_gia_ergasia.isSelected() == true){
        CheckBox_Ekpaideush.add("Εργάζεται συστηματικά και μεθοδικά, με εργατικότητα  και συνέπεια στις υποχρεώσεις του.");
         }
         else{
             CheckBox_Ekpaideush.remove("Εργάζεται συστηματικά και μεθοδικά, με εργατικότητα  και συνέπεια στις υποχρεώσεις του.");
         }
    }                                                                     

    private void Dianoitikes_ikanotitesActionPerformed(java.awt.event.ActionEvent evt) {                                                       
       if (Dianoitikes_ikanotites.isSelected() == true){
        CheckBox_Ekpaideush.add("Η δυνατότητα λήψης αποφάσεων σε συνθήκες αβεβαιότητας και η αναζήτηση ευκαιριών ήταν ένα απο τα μεγάλα του προσόντα.");
         }
         else{
             CheckBox_Ekpaideush.remove("Η δυνατότητα λήψης αποφάσεων σε συνθήκες αβεβαιότητας και η αναζήτηση ευκαιριών ήταν ένα απο τα μεγάλα του προσόντα.");
         }
    }                                                      

    private void Ereunitikes_ikanotitesActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        if (Ereunitikes_ikanotites.isSelected() == true){
        CheckBox_Ekpaideush.add("Είναι πρόθυμος να αναλάβει οποιαδήποτε δραστηριότητα του ανατεθεί και να αζητήσει νέες λύσεις.");
         }
         else{
             CheckBox_Ekpaideush.remove("Είναι πρόθυμος να αναλάβει οποιαδήποτε δραστηριότητα του ανατεθεί και να αζητήσει νέες λύσεις.");
         }
    }                                                      

    private void Synaisthimatiki_statherotita_kai_orimotitaActionPerformed(java.awt.event.ActionEvent evt) {                                                                           
        if (Synaisthimatiki_statherotita_kai_orimotita.isSelected() == true){
        CheckBox_Ekpaideush.add("Δεν παρασύρετε συναισθηματικά στο χώρο του, πράγμα που σημαίνει πως δύσκολα θα πάρει βιαστικές και λανθασμένες αποφάσεις.");
         }
         else{
             CheckBox_Ekpaideush.remove("Δεν παρασύρετε συναισθηματικά στο χώρο του, πράγμα που σημαίνει πως δύσκολα θα πάρει βιαστικές και λανθασμένες αποφάσεις.");
         }
    }                                                                          

    private void Syggrafiki_ikanotitaActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        if (Syggrafiki_ikanotita.isSelected() == true){
        CheckBox_Ekpaideush.add("Προβάλλει τις αναφορές του τεκμηριωμένες και με πειθώ για να προσελκύσει το ενδιαφέρον.");
         }
         else{
             CheckBox_Ekpaideush.remove("Προβάλλει τις αναφορές του τεκμηριωμένες και με πειθώ για να προσελκύσει το ενδιαφέρον.");
         }
    }                                                    

    private void SynergatikotitaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        if (Synergatikotita.isSelected() == true){
        CheckBox_Ekpaideush.add("Καλές ακαδημαϊκές επιδόσεις και συνεργατικότητα τοσο με συναδέλφους του όσο και με το διδακτικό προσωπικό.");
         }
         else{
             CheckBox_Ekpaideush.remove("Καλές ακαδημαϊκές επιδόσεις και συνεργατικότητα τοσο με συναδέλφους του όσο και με το διδακτικό προσωπικό.");
         }
    }                                               

    private void Dimiourgikotita_kai_prototipiaActionPerformed(java.awt.event.ActionEvent evt) {                                                               
        if (Dimiourgikotita_kai_prototipia.isSelected() == true){
        CheckBox_Ekpaideush.add("Η προβολή καινοτόμων και αποτελεσματικών ιδεών αποτέλεσαν ένα ισχυρό πλεονέκτημά του.");
         }
         else{
             CheckBox_Ekpaideush.remove("Η προβολή καινοτόμων και αποτελεσματικών ιδεών αποτέλεσαν ένα ισχυρό πλεονέκτημά του.");
         }
    }                                                              

    private void Akeraiotita_xaraktiraActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        if (Akeraiotita_xaraktira.isSelected() == true){
        CheckBox_Ekpaideush.add("Πρόκειται για ένα άτομο με ισχυρό χαρακτήρα που καθοδηγεί και εμπνέει εμπιστοσύνη.");
         }
         else{
             CheckBox_Ekpaideush.remove("Πρόκειται για ένα άτομο με ισχυρό χαρακτήρα που καθοδηγεί και εμπνέει εμπιστοσύνη.");
         }
    }                                                     

    private void AllaMouseClicked(java.awt.event.MouseEvent evt) {         
        alla1 = "True";
        Alla.setText("");
    }                                 

    private void Mati1MouseEntered(java.awt.event.MouseEvent evt) {                                   
        Mati1.setToolTipText("Εργάζεται συστηματικά και μεθοδικά, με εργατικότητα  και συνέπεια στις υποχρεώσεις του.");
    }                                  

    private void Mati2MouseEntered(java.awt.event.MouseEvent evt) {                                   
        Mati2.setToolTipText("Η δυνατότητα λήψης αποφάσεων σε συνθήκες αβεβαιότητας και η αναζήτηση ευκαιριών ήταν ένα απο τα μεγάλα του προσόντα.");
    }                                  

    private void Mati3MouseEntered(java.awt.event.MouseEvent evt) {                                   
        Mati3.setToolTipText("Είναι πρόθυμος να αναλάβει οποιαδήποτε δραστηριότητα του ανατεθεί και να αζητήσει νέες λύσεις.");
    }                                  

    private void Mati4MouseEntered(java.awt.event.MouseEvent evt) {                                   
        Mati4.setToolTipText("Δεν παρασύρετε συναισθηματικά στο χώρο του, πράγμα που σημαίνει πως δύσκολα θα πάρει βιαστικές και λανθασμένες αποφάσεις.");
    }                                  

    private void Mati5MouseEntered(java.awt.event.MouseEvent evt) {                                   
        Mati5.setToolTipText("Προβάλλει τις αναφορές του τεκμηριωμένες και με πειθώ για να προσελκύσει το ενδιαφέρον.");
    }                                  

    private void Mati7MouseEntered(java.awt.event.MouseEvent evt) {                                   
        Mati7.setToolTipText("Καλές ακαδημαϊκές επιδόσεις και συνεργατικότητα τοσο με συναδέλφους του όσο και με το διδακτικό προσωπικό.");
    }                                  

    private void Mati8MouseEntered(java.awt.event.MouseEvent evt) {                                   
        Mati8.setToolTipText("Η προβολή καινοτόμων και αποτελεσματικών ιδεών αποτέλεσαν ένα ισχυρό πλεονέκτημά του.");
    }                                  

    private void Mati10MouseEntered(java.awt.event.MouseEvent evt) {                                    
        Mati10.setToolTipText("Πρόκειται για ένα άτομο με ισχυρό χαρακτήρα που καθοδηγεί και εμπνέει εμπιστοσύνη.");
    }                                   

    private void Pedio_spoudon_textMouseClicked(java.awt.event.MouseEvent evt) {  
        pedio="True";
        Pedio_spoudon_text.setText("Καλή γνώση του ");
    }                                               

    private void Eidikes_ikanotites_textMouseClicked(java.awt.event.MouseEvent evt) { 
        eidikes = "True";
        Eidikes_ikanotites_text.setText("Επιπλέον ο υποψήφιος διαθέτει ");
    }                                                    

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {                                    
        Oroi_Xrisis ox = new Oroi_Xrisis();
        ox.setVisible(true);
        setVisible(false);
        dispose();
    }                                   

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {                                     
        System.exit(0);
    }                                    

    private void HelpMouseClicked(java.awt.event.MouseEvent evt) {                                  
        Help help = new Help();
        help.setVisible(true);
    }                                 

    private void AboutMouseClicked(java.awt.event.MouseEvent evt) {                                   
        About about = new About();
        about.setVisible(true);
    }                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckBox_Ekpaideush.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckBox_Ekpaideush.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckBox_Ekpaideush.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckBox_Ekpaideush.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckBox_Ekpaideush().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenu About;
    private javax.swing.JCheckBox Akeraiotita_xaraktira;
    private javax.swing.JTextArea Alla;
    private javax.swing.JLabel Deksiotites;
    private javax.swing.JCheckBox Dianoitikes_ikanotites;
    private javax.swing.JCheckBox Dimiourgikotita_kai_prototipia;
    private javax.swing.JCheckBox Drastiriotita_kai_thelisi_gia_ergasia;
    private javax.swing.JLabel Eidikes_ikanotites;
    private javax.swing.JTextArea Eidikes_ikanotites_text;
    private javax.swing.JButton Epomeno;
    private javax.swing.JCheckBox Ereunitikes_ikanotites;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Help;
    private javax.swing.JLabel Mati1;
    private javax.swing.JLabel Mati10;
    private javax.swing.JLabel Mati2;
    private javax.swing.JLabel Mati3;
    private javax.swing.JLabel Mati4;
    private javax.swing.JLabel Mati5;
    private javax.swing.JLabel Mati7;
    private javax.swing.JLabel Mati8;
    private javax.swing.JMenuItem New;
    private javax.swing.JLabel Pedio_spoudon;
    private javax.swing.JTextArea Pedio_spoudon_text;
    private javax.swing.JButton Prohgoymeno;
    private javax.swing.JCheckBox Syggrafiki_ikanotita;
    private javax.swing.JCheckBox Synaisthimatiki_statherotita_kai_orimotita;
    private javax.swing.JCheckBox Synergatikotita;
    private javax.swing.JLabel akadimaiki_ekpedeusi;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel ypodiksi1;
    // End of variables declaration                   
}
